---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the python dependencies
  apt: name={{ item }} state=present
  with_items: python-software-properties
  environment: env

- name: Modify repo to get latest redis-server
  apt_repository: repo='ppa:chris-lea/redis-server'
  when: ansible_os_family == "Debian"

- name: Install the Redis packages 
  apt: name={{ item }} state=present update_cache=yes
  with_items: redis_ubuntu_pkg
  environment: env
  when: ansible_os_family == "Debian"

- name: Copy the redis configuration file 
  template: src=redis.conf.j2 dest={{ redis_conf_dest }}
  notify: 
   - restart redis 

- name: Set the kernel paramter for vm overcommit 
  sysctl: name=vm.overcommit_memory value=1 state=present

- name: start the redis service
  service: name={{ redis_service }} state=started enabled=yes

