---
- hosts: all
  sudo: true
  tasks:
    # BASIC DEPENDENCIES
    # ==================
    - name: update apt source
      copy: src=files/sources.list dest=/etc/apt/sources.list

    - name: apt-get update
      apt: update_cache=yes

    - name: install essential packages
      apt: pkg={{ item }} state=installed
      sudo: true
      with_items:
        - build-essential
        - wget
        - curl
        - tmux
        #- ufw
        - git-core
        - nodejs
        - imagemagick
        - vim
        - qrencode
        - libqrencode-dev
        - libmysqlclient18
        - libmysqlclient-dev
        #- fail2ban
        # for test & development only
        #- libqtwebkit-dev
        #- libsqlite3-dev
        - sendmail

- hosts: all
  roles:
  # https://galaxy.ansible.com/list#/roles/335
  - role: sgmac.rbenv
    user: "{{ app_user }}"
    ruby_version: 2.1.0
    sh: bash
